### PR TITLE
FMC navdata and calculation plugin

### PR DESCRIPTION
**Pull request by remenkemi**

### CODE REVIEW

**Comment by crazytimtimtim** [comment]
### To-Do list:
- [x] Implementation of REF NAV DATA page(FMC side)
- [ ] Implementation of REF NAV DATA page(CDU side)
- [x] Implementation of RTE1 page(FMC side)
- [ ] Implementation of RTE1 page(CDU side)
- [ ] Implementation of NAV RADIO page(FMC side)
- [ ] Implementation of NAV RADIO page(CDU side)
- [x] Implementation of SEL DESIRED WPT page(FMC side)
- [ ] Implementation of SEL DESIRED WPT page(CDU side)
- [ ] Partial implementation of POS REF page(radio position only, FMC side)
- [ ] Partial implementation of POS REF page(radio position only, CDU side)

**Comment by remenkemi** [comment]
Waiting on 2 fixes:
@BRUHegg: fix indentation of POI names on SEL DESIRED WAYPOINT
@remenkemi: fix fmc braking when selecting certain incomplete pages

**Comment by remenkemi** [comment]
I need to double check select desired wpt to make sure all poi types are displaying correctly, otherwise this is ready to merge

**Comment by remenkemi** [comment]
This is ultimately waiting on @nathroxer to at least finish the MCP remodel so we can implement the button lights.

**Comment by remenkemi** [comment]
This will be merged as soon as @nathroxer can finish the mcp remodeling so we can adjust the manipulators and button lights. We can continue working on navrad, fixinfo, and legs/rte1 on master along with the autopilot after that.

**Comment by remenkemi** [comment]
@BRUHegg Do want to review this before I fix the conflicts and merge?

**Comment by remenkemi** [comment]
@BRUHegg I figured out the mcp button issue. But should the buttons be toggling the datarefs rather than just setting them to 1? I would like to hurry up and merge because this is less broken than master right now lol.

**Pull request merged**
