### PR TITLE
Checklist enhancement

### PR DESCRIPTION
**Pull request by Ker1010**
**Expected**
Completely _Normal Manu_, _Reset_ page. _I want to make non-normal if possible_

#
**Preview**
Screenshot 2023-08-02 193410
#

>this pull request still WIP please don't merge atm, very welcome for work togerther
>Discord: Ker_1010 and this is my first work aircraft for xplane some hard for me 💀

### CODE REVIEW

**Comment by Ker1010** [comment]
**Preview**
image
last improvement for [fa3f77a](https://github.com/Stratosphere-Studios/777-300ER/pull/103/commits/fa3f77ae4f8130878a5a89ffc413f1ff9bcc04f3)
#
**Problem**
I'm trying to create new boxes but It seems to be done using numbers but why use addition instead of numbers directly?
example
image

I know that seems to be used for better classification, but is there any way I can identify it?

**Comment by crazytimtimtim** [comment]
@IASXP

**Comment by IASXP** [comment]
> **Preview** image last improvement for [fa3f77a](https://github.com/Stratosphere-Studios/777-300ER/pull/103/commits/fa3f77ae4f8130878a5a89ffc413f1ff9bcc04f3)
> 
> **Problem** I'm trying to create new boxes but It seems to be done using numbers but why use addition instead of numbers directly? example image
> 
> I know that seems to be used for better classification, but is there any way I can identify it?

1. Those are just for the top three boxes for reset, normal menu, and non-normal menu.
2. The reason I used the numbers is since for me its faster to just use addition to quickly move it to the spot I want it to be at.
3. There is no performance degradation by doing this but I understand it makes the code harder to read. I'll get around to fixing it soon.

**Comment by Ker1010** [comment]
nice to see you again here, but yeah I decided to split this pull request into 2 block, this is block 1 
there are so many problems I don't know how to fix

example 
1. if this list don't have _checkMark_ should don't boxing _surroun2_
2. the buttons below have no function
3. _value = 3_ can't change automatically when it completed, some for ChecklistComplete it'll skip it

anyway this pull request ready for departure, hope see you on block 2 😉

**Pull request merged**
