### PR TITLE
Tail remodeling and improved animations on wing and tails

### PR DESCRIPTION
**Pull request by ArnavSharmaz0602**

### CODE REVIEW

**Comment by ArnavSharmaz0602** [comment]
An addon for the 777-300ERF is added, but still not yet usable. Work still pending, and will be done.

**Comment by ArnavSharmaz0602** [comment]
Added new acf file for 300ERF variant. Texturing still pending for the cargo bay obj, but will soon be done. Remodeled the fuse 1 obj and retextured all 3 fuse objs. Cargo bay animations have been improved as well. Paintkits for the 300ERF fuselage are also available now.

**Review by ArnavSharmaz0602 — COMMENTED** [review]
Addons and Changes....

**Comment by crazytimtimtim** [comment]
Nice! I'm just worried about your modifications to existing objects like the wings. Maybe just find a way to work with @nathroxer to get those changes done because they'll get overwritten whenever he modifies them.

**Comment by ArnavSharmaz0602** [comment]
> Nice! I'm just worried about your modifications to existing objects like the wings. Maybe just find a way to work with @nathroxer to get those changes done because they'll get overwritten whenever he modifies them.

Well the animations were lengthened to eliminate problems of mesh overlapping, which are not visible in small keyframe intervals like between 0 and 2.

**Comment by ArnavSharmaz0602** [comment]
Updated CargoBay.obj file with new textures and removed doors_ERF.obj as it was not needed.

**Comment by ArnavSharmaz0602** [comment]
New textures for CargoBay.obj and cleaned up mess of UV mapping for tail.obj

**Comment by crazytimtimtim** [comment]
Ok, will merge once you say it's ready and @nathroxer and you sort out the changes to the existing models. The easiest way might be to just give him the .blend files.

**Comment by crazytimtimtim** [comment]
@nathroxer ?

**Comment by crazytimtimtim** [comment]
@nathroxer @ArnavSharmaz0602 Just want to remind you this still exists...

**Comment by crazytimtimtim** [comment]
We already include your erf mod so that can be removed from this pull request. As for the other stuff you'll need to sort out what you changed and what to keep with @nathroxer

**Comment by crazytimtimtim** [comment]
Hi, do you think you can create a new pull request that doesn't include the engines, freighter acf, or freighter objs?
Please also summarize what you changed in each file.

**Comment by remenkemi** [comment]
I'm gonna close this if nobody is gonna do anything. @ArnavSharmaz0602? @nathroxer?
Please, once again make a new pull request without the engines (have been remodeled) and the ERF (already included). Please also explain what changes you made to the remaining files so we can sort out a way to get them implemented.

**Comment by remenkemi** [comment]
Will reopen of @ArnavSharmaz0602 responds

**Pull request closed without merging**
